### ISSUE TITLE
Syntax Error when enabling Memories app

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#14]
I've followed the installation instructions, but when trying to run the `index` occ command, I'm getting a syntax error:
```
sudo -u www-data php /var/www/nextcloud/occ apps:memories
An unhandled exception has been thrown:
ParseError: syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE) in /var/www/nextcloud/apps/memories/lib/Db/TimelineWrite.php:58
Stack trace:
#0 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 /var/www/nextcloud/apps/memories/lib/Command/Index.php(79): spl_autoload_call()
#3 [internal function]: OCA\Memories\Command\Index->__construct()
#4 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(108): ReflectionClass->newInstanceArgs()
#5 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->buildClass()
#6 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve()
#7 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\Utility\SimpleContainer->query()
#8 /var/www/nextcloud/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#9 /var/www/nextcloud/lib/private/Console/Application.php(217): OC\ServerContainer->query()
#10 /var/www/nextcloud/lib/private/Console/Application.php(128): OC\Console\Application->loadCommandsFromInfoXml()
#11 /var/www/nextcloud/console.php(99): OC\Console\Application->loadCommands()
#12 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#13 {main}user@hostname:/var/www/nextcloud/apps#
```

This syntax error throws an internal server error in nextcloud which prevents all nextcloud access:
![image](https://user-images.githubusercontent.com/10717998/185961983-24fca725-e2ca-4da6-93d3-c2a79cf3ec24.png)

**Comment by pulsejet** [comment]
Which php version are you running?

**Comment by pulsejet** [comment]
Try now

**Comment by meichthys** [comment]
> Which php version are you running?

PHP 7.4.3
Trying now...

**Comment by pulsejet** [comment]
I just rebuilt the js, so you might need to clear cache (#10)

**Comment by meichthys** [comment]
It's indexing now 👍
I do still have the internal server error even after clearing the cache, but only for memories now. I'm assuming that it will take care of itself after the indexing is finished?

**Comment by pulsejet** [comment]
Huh you've two errors? What does the internal server error say?

**Comment by meichthys** [comment]
![image](https://user-images.githubusercontent.com/10717998/185993197-329cf932-b9d3-4ec8-b458-ca7f3a58abbf.png)

The Memories app seems to be the only app that is affected.

**Comment by pulsejet** [comment]
That isn't an error log ... I need the stuff below this (in debug mode)

**Comment by meichthys** [comment]
I'm not sure how to enable debug mode, but i do see this in nextcloud.log:

```"app":"index","method":"GET","url":"/apps/memories/","message":"syntax error, unexpected ')', expecting variable (T_VARIABLE)"```

**Comment by pulsejet** [comment]
Just set debug => true in `config.php`. Need more details than this.

**Comment by meichthys** [comment]
Looks like the indexing failed half way:
![image](https://user-images.githubusercontent.com/10717998/185994233-92f584c0-a515-4a49-b46e-6e6431aaefed.png)

I'll set debug mode and see what else i can find.

**Comment by meichthys** [comment]
Here's the debug log information:
```
    Request ID: o4Vx6n5gBK0LzM5JHREh
    Type: ParseError
    Code: 0
    Message: syntax error, unexpected ')', expecting variable (T_VARIABLE)
    File: /var/www/nextcloud/apps/memories/lib/Controller/PageController.php
    Line: 31


Trace

#0 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 [internal function]: spl_autoload_call()
#3 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): ReflectionClass->__construct()
#4 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve()
#5 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\Utility\SimpleContainer->query()
#6 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(437): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#7 /var/www/nextcloud/lib/private/AppFramework/App.php(159): OC\AppFramework\DependencyInjection\DIContainer->query()
#8 /var/www/nextcloud/lib/private/Route/Router.php(298): OC\AppFramework\App::main()
#9 /var/www/nextcloud/lib/base.php(1023): OC\Route\Router->match()
#10 /var/www/nextcloud/index.php(36): OC::handleRequest()
#11 {main}
```

**Comment by pulsejet** [comment]
You gotta be kidding... give me a few minutes

**Comment by pulsejet** [comment]
Okay, hopefully fixed now. Try indexing again; it should resume (quickly catch up to) from where it stopped.

**Comment by pulsejet** [comment]
That is super strange. What db/version is this?

**Comment by meichthys** [comment]
Nextcloud 24.0.3
Database: PostgreSQL 12.12

**Comment by pulsejet** [comment]
I can't repro with the same versions of everything. Maybe I need to run the VM itself, but it's still strange.
Open a new issue for this if it persists.

**Comment by meichthys** [comment]
The issue still persists but it seems like all of the photos were indexed and show up fine in the app. I won't worry about it right now.

**Comment by pulsejet** [comment]
It will be a problem only if you edit the exif data on any of the photos.

**Comment by meichthys** [comment]
Good to know. Thanks.
