### ISSUE TITLE
Error: Only variables should be passed by reference

### ISSUE THREAD

**Issue by teemue** [pulsejet/memories#25]
Hi! Thanks for the app.
At least the latest 1.0.7 version throws following errors in the nc log:

Error: Only variables should be passed by reference at /var/www/html/custom_apps/memories/lib/Controller/PageController.php#58

Error: Only variables should be passed by reference at /var/www/html/custom_apps/memories/lib/Controller/PageController.php#77

Error: Only variables should be passed by reference at /var/www/html/custom_apps/memories/lib/Controller/PageController.php#92

**Comment by puregreen59** [comment]
Getting same problem

**Comment by pulsejet** [comment]
This is fixed on master. Look for the next release (probably today)

**Comment by Aquariu** [comment]
Thank you for this app in general and for raising this issue in particular.

In my situation this message pops up in the logs while trying to load a Timeline based on a folder in an External Storage.
The loading of the timeline is ok when chosing a local folder.
I was about to create a specific issue for External Storage but will wait to see if this fix applies to my specific issue.
Configuration : Debian 11, NC 24.0.5, mariadb, SFTP external storage.

**Comment by pulsejet** [comment]
That is unrelated. Lets track that in

**Comment by kotjarka** [comment]
Problem still exists in memories 4.11.0 (lot identical positions in nextcloudlog):
```
[PHP] Error: Error: Only variables should be passed by reference at /var/www/nextcloud/apps/memories/lib/Controller/PlacesController.php#93 at <<closure>>

0. /var/www/nextcloud/apps/memories/lib/Controller/PlacesController.php line 93
   OC\Log\ErrorHandler::onError()
1. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
   OCA\Memories\Controller\PlacesController->preview()
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
   OC\AppFramework\Http\Dispatcher->executeController()
3. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
4. /var/www/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
5. /var/www/nextcloud/lib/base.php line 1047
   OC\Route\Router->match()
6. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

GET /nextcloud/apps/memories/api/places/preview/2668413
from 192.168.1.75 by user at 2023-02-18T20:51:19+01:00
```

**Comment by pulsejet** [comment]
That slipped through somehow. You can patch it up with https://github.com/pulsejet/memories/commit/bdbce20f91b7938fb33ae49962111bb000d60ffc for now

**Comment by simonspa** [comment]
This resurfaced for me when updating to 5.2.0 and re-indexing places:

```
{"reqId":"e5MtMVBZt29aMeU07OmY","level":3,"time":"2023-06-30T20:56:51+02:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Only variables should be passed by reference at /var/www/nextcloud/apps/memories/lib/Db/TimelineWritePlaces.php#53","userAgent":"--","version":"26.0.3.2","data":{"app":"PHP"},"id":"64a25b9367d3a"}
```
