### ISSUE TITLE
Shared Galery Rename or Move Only user "xy" can update this person

### ISSUE THREAD

**Issue by apg1980** [pulsejet/memories#290]
i open this ticket in case of the developers on the recognize app, told me this is an memories issue.

Which version of memories are you using?

4.9.2
Enabled Modes

Object recognition, Face recognition
TensorFlow mode

Normal mode
Which Nextcloud version do you have installed?

25.0.2
Which Operating system do you have installed?

Ubuntu 22.04
Which Docker container are you using to run Nextcloud? (if applicable)

How much RAM does your server have?

12gb
What processor Architecture does your CPU have?

x64
Describe the Bug

I share my whole image galery with my wife and she is uploading her images in this galery as well.
facerecoginition with my account quits the option for move faces to another cluster or rename the cluster with "Only user "xx" can update this person".
This appears by images uploadet and created from user of my wife in my galery share.
I cannot manage my galery´s faces anymore.
any tips appreciate

to descrive my issue more detailed.
i have on my account an folder names Galery which is shared with my wife (fullpermissions).
i am uploading from nextcloud app images and videos via auto upload and my wife up to this folder as well.
with the latest 2 versions of recognize or i dont know the nextcloud 25.0.2 i cannot move recognized persons to another cluster if my wife shot those images. the error in the topic appears.
if i try to move the images to another cluster from my wifes account i got an error move of image xy failed. no further entrys in the log.
this is an serious issue for me i cannot organize my structure anymore.
are here any tips?

best regards
Expected Behavior

able to move or rename faces

**Comment by pulsejet** [comment]
So, faces in recognize are owned by users rather than according to the folder. As a result, this is impossible to fix.

A possible solution would be to use external storage or a group folder instead, where everything is owned by a common user. Ideally though, we need a better solution, e.g. shared ownership of files that recognize recognizes (wink).

**Comment by jerrac** [comment]
Er, I started watching this issue because I was running into that message on pictures stored in a group folder. As in a folder created by the Group folders app.

Do you know if those folders are implemented the same way as normal shared folders?

**Comment by apg1980** [comment]
pictures are stored in my account. folder with images are shared to my wife in which she is uploading images as well.

**Comment by pulsejet** [comment]
> Er, I started watching this issue because I was running into that message on pictures stored in a group folder. As in a folder created by the Group folders app.

Hmm, then I incorrectly assumed group folders have common ownership.

> pictures are stored in my account. folder with images are shared to my wife in which she is uploading images as well.

So as I said, this is problematic. If Alice owns some photos and Bob owns others, then Alice will have some clusters, Bob will have other clusters, and you can't mix between these now.

Somebody needs to take a closer look at this.

**Comment by EVOTk** [comment]
If two clusters have the same "name", wouldn't it be possible to display them in the same "folder" and then propose one or the other cluster?

Exemple :
![image](https://user-images.githubusercontent.com/45015615/223811446-cd12f8cb-aa1f-4726-916a-38dc9bde90ed.png)

![image](https://user-images.githubusercontent.com/45015615/223813698-603b9e7d-7172-4e16-8af8-b84d80f601bb.png)

![image](https://user-images.githubusercontent.com/45015615/223815540-089b8512-74f6-4cd3-816b-73fdd1677702.png)

I don't know if I understand, sorry i'm french, but the idea is that when two clusters have the same name, Memories will make a sub-category, and then display the clusters of each user

**Comment by apg1980** [comment]
the latest version after scan over all images and users, displays now each cluster twice, on cluster is from my wifes account (with my shares folder) an one from me, the ones from my wifes account i cannot move and the error appears.

**Comment by EVOTk** [comment]
> the latest version after scan over all images and users, displays now each cluster twice, on cluster is from my wifes account (with my shares folder) an one from me, the ones from my wifes account i cannot move and the error appears.

Yes, it's recognize behavior changed
https://github.com/pulsejet/memories/issues/500

**Comment by apg1980** [comment]
oh no thats not good to See everything twice, not sexy

**Comment by EVOTk** [comment]
Yes
@pulsejet seems to be working on a way to make it more attractive: 
https://github.com/pulsejet/memories/issues/462

**Comment by pulsejet** [comment]
This is fixed in 4.12.4

**Comment by EVOTk** [comment]
After the update, the clusters of other users who share photos with me have completely disappeared

**Comment by pulsejet** [comment]
Maybe you need to run some recognize command. Basically all clusters and detections are now replicated across all users, and you see only your own clusters.

**Comment by vwbusguy** [comment]
I am still seeing clusters of other users in memories that I can't update/rename.  I tried a force reindexing and am still seeing this.  They aren't clusters I see in facerecognition but clusters associated with another user that are still showing up in Memories for my user.

**Comment by sirdrakeistda** [comment]
@pulsejet I think there is a more severe issue. At the moment I see names in one account, which I never created. Following happened:
1. account1 shared folder with account2
2. account1 sees names which account2 created, if (false) recognized in own images
3. This problem persists still, when the shared folder get's unshared

This does not happen in the facerecognition app (in the settings it's possible to cluster images in facerecognition), but only in the facerecognition frontend of memories.

Whats should happen:
account1 should only see names of persons clustered on account one or explicit allowed to be seen by account2. Otherwise I could share folders and then I'm able to identify the names of the clusters in another account. Also there should be removed permissions when unsharing a folder. For me it seems kind of a security issue, which I can't prevent (my clusternames get shared as soon someone shares a folder with me).
